# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/asideCard_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asideCard(object):
    def setupUi(self, asideCard):
        asideCard.setObjectName("asideCard")
        asideCard.resize(280, 180)
        asideCard.setMinimumSize(QtCore.QSize(280, 180))
        asideCard.setStyleSheet("#asideCard{\n"
"    border: 1px solid #808080;\n"
"    border-radius: 8px;\n"
"}")
        self.label = QtWidgets.QLabel(asideCard)
        self.label.setGeometry(QtCore.QRect(60, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #262626\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(asideCard)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 38, 38))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: #313743;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/bolt-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(asideCard)
        self.frame.setGeometry(QtCore.QRect(180, 20, 6, 20))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(asideCard)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #262626;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(asideCard)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #262626;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(asideCard)
        self.horizontalSlider.setGeometry(QtCore.QRect(59, 80, 161, 31))
        self.horizontalSlider.setStyleSheet("QSlider:horizontal {\n"
"    /* Add space on the sides for the large handle to be fully visible at min/max positions */\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    /* --- TRACK (GROOVE) STYLING --- */\n"
"    \n"
"    /* Uniform light gray color for the entire track as shown in the image */\n"
"    background: #e0e0e0;\n"
"    \n"
"    /* Set the track height */\n"
"    height: 8px;\n"
"    \n"
"    /* Fully rounded ends */\n"
"    border-radius: 4px;\n"
"    \n"
"    /* Prevent borders from showing */\n"
"    border: none;\n"
"}\n"
"\n"
"/* Ensure the sub-page (filled portion) and add-page (unfilled portion) match the groove */\n"
"QSlider::sub-page:horizontal,\n"
"QSlider::add-page:horizontal {\n"
"    background: #e0e0e0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    /* --- HANDLE (THUMB) STYLING --- */\n"
"    \n"
"    /* Dimensions: 20px diameter circle */\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    \n"
"    /* Center the 20px handle vertically on the 8px groove: (20 - 8) / 2 = 6px negative margin */\n"
"    margin: -8px 0;\n"
"    \n"
"    /* Make it a perfect circle */\n"
"    border-radius: 10px;\n"
"    \n"
"    /* White center fill */\n"
"    background: white;\n"
"    \n"
"    /* The bright purple ring/outline */\n"
"    border: 3px solid #7e55ff;\n"
"    \n"
"    /* The crucial glow effect using box-shadow */\n"
"    box-shadow: 0 0 8px rgba(126, 85, 255, 0.6);\n"
"}\n"
"\n"
"/* Optional: Subtle changes when the user hovers over the handle */\n"
"QSlider::handle:horizontal:hover {\n"
"    border-color: #6a3dff; /* Slightly darker purple on hover */\n"
"    box-shadow: 0 0 10px rgba(106, 61, 255, 0.8); /* Stronger glow on hover */\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.frame_2 = QtWidgets.QFrame(asideCard)
        self.frame_2.setGeometry(QtCore.QRect(190, 20, 6, 20))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(asideCard)
        self.frame_3.setGeometry(QtCore.QRect(200, 20, 6, 20))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(asideCard)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(asideCard)
        self.label_5.setGeometry(QtCore.QRect(230, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(asideCard)
        self.frame_4.setGeometry(QtCore.QRect(170, 130, 92, 32))
        self.frame_4.setStyleSheet("QFrame{\n"
"    border: 1px solid #808080;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(10, 8, 71, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(asideCard)
        self.line.setGeometry(QtCore.QRect(-3, 110, 291, 20))
        self.line.setStyleSheet("Line{\n"
"    color: #808080;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(asideCard)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius: 4px;\n"
"    border: 1px solid #808080;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(asideCard)
        QtCore.QMetaObject.connectSlotsByName(asideCard)

    def retranslateUi(self, asideCard):
        _translate = QtCore.QCoreApplication.translate
        asideCard.setWindowTitle(_translate("asideCard", "Form"))
        self.label.setText(_translate("asideCard", "0123456789"))
        self.label_2.setText(_translate("asideCard", "PR101"))
        self.label_3.setText(_translate("asideCard", "PR102"))
        self.label_4.setText(_translate("asideCard", "On Ope"))
        self.label_5.setText(_translate("asideCard", "24 %"))
        self.pushButton_2.setText(_translate("asideCard", "AGV-101"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    asideCard = QtWidgets.QWidget()
    ui = Ui_asideCard()
    ui.setupUi(asideCard)
    asideCard.show()
    sys.exit(app.exec_())
