# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/asideCardVehicle.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asideCardVehicle(object):
    def setupUi(self, asideCardVehicle):
        asideCardVehicle.setObjectName("asideCardVehicle")
        asideCardVehicle.setEnabled(True)
        asideCardVehicle.resize(280, 180)
        asideCardVehicle.setMinimumSize(QtCore.QSize(280, 180))
        asideCardVehicle.setStyleSheet("#asideCardVehicle{\n"
"    border: 1px solid #808080;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(asideCardVehicle)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 38, 38))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: #313743;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/paper-plane-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(asideCardVehicle)
        self.label.setGeometry(QtCore.QRect(60, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #262626\n"
"}")
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(asideCardVehicle)
        self.frame_4.setGeometry(QtCore.QRect(170, 130, 92, 32))
        self.frame_4.setStyleSheet("QFrame{\n"
"    border: 1px solid #808080;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(10, 8, 71, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame_2 = QtWidgets.QFrame(asideCardVehicle)
        self.frame_2.setGeometry(QtCore.QRect(240, 20, 6, 20))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(asideCardVehicle)
        self.frame_3.setGeometry(QtCore.QRect(250, 20, 6, 20))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(asideCardVehicle)
        self.frame.setGeometry(QtCore.QRect(230, 20, 6, 20))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #3AC2A5;\n"
"    width: 6px;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pbInspect = QtWidgets.QPushButton(asideCardVehicle)
        self.pbInspect.setGeometry(QtCore.QRect(70, 130, 91, 31))
        self.pbInspect.setStyleSheet("QPushButton{\n"
"    border-radius: 4px;\n"
"    border: 1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e3e3e3;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbInspect.setIcon(icon1)
        self.pbInspect.setObjectName("pbInspect")
        self.pushButton_3 = QtWidgets.QPushButton(asideCardVehicle)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 90, 91, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius: 4px;\n"
"    border: 1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e3e3e3;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("AppDesign\\../icons/retweet-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(asideCardVehicle)
        self.label_4.setGeometry(QtCore.QRect(40, 71, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(asideCardVehicle)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 66, 31, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"}")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("AppDesign\\../icons/clock-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(22, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(asideCardVehicle)
        self.label_5.setGeometry(QtCore.QRect(40, 90, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: #262626\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(asideCardVehicle)
        self.label_6.setGeometry(QtCore.QRect(190, 20, 41, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(asideCardVehicle)
        self.line.setGeometry(QtCore.QRect(0, 50, 291, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")

        self.retranslateUi(asideCardVehicle)
        QtCore.QMetaObject.connectSlotsByName(asideCardVehicle)

    def retranslateUi(self, asideCardVehicle):
        _translate = QtCore.QCoreApplication.translate
        asideCardVehicle.setWindowTitle(_translate("asideCardVehicle", "Form"))
        self.label.setText(_translate("asideCardVehicle", "AGV-101"))
        self.pbInspect.setText(_translate("asideCardVehicle", "AGV-101"))
        self.pushButton_3.setText(_translate("asideCardVehicle", "Automatic"))
        self.label_4.setText(_translate("asideCardVehicle", "Usage Time"))
        self.label_5.setText(_translate("asideCardVehicle", "12 Hour"))
        self.label_6.setText(_translate("asideCardVehicle", "24 ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    asideCardVehicle = QtWidgets.QWidget()
    ui = Ui_asideCardVehicle()
    ui.setupUi(asideCardVehicle)
    asideCardVehicle.show()
    sys.exit(app.exec_())
