# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/asideCardInspect.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asideCardInspect(object):
    def setupUi(self, asideCardInspect):
        asideCardInspect.setObjectName("asideCardInspect")
        asideCardInspect.resize(323, 531)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        asideCardInspect.setWindowIcon(icon)
        asideCardInspect.setStyleSheet("#asideCardInspect{\n"
"    background-color: #f5f5f5;\n"
"    border-radius: 6px;\n"
"}")
        self.frame_ultrasonic = QtWidgets.QFrame(asideCardInspect)
        self.frame_ultrasonic.setGeometry(QtCore.QRect(20, 260, 111, 101))
        self.frame_ultrasonic.setStyleSheet("#frame_ultrasonic{\n"
"    background-color:white;\n"
"    border: 1px solid #808080;\n"
"    border-radius: 8px;\n"
"}")
        self.frame_ultrasonic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ultrasonic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ultrasonic.setObjectName("frame_ultrasonic")
        self.label_3 = QtWidgets.QLabel(self.frame_ultrasonic)
        self.label_3.setGeometry(QtCore.QRect(43, 16, 47, 13))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_ultrasonic)
        self.pushButton.setGeometry(QtCore.QRect(6, 6, 32, 32))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color: #ebebeb;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/satellite-dish-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame_ultrasonic)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_ultrasonic)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_ultrasonic)
        self.label_6.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(asideCardInspect)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(asideCardInspect)
        self.label_2.setGeometry(QtCore.QRect(40, 34, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lamp = QtWidgets.QFrame(asideCardInspect)
        self.lamp.setGeometry(QtCore.QRect(20, 34, 14, 14))
        self.lamp.setStyleSheet("background-color: gray;\n"
"border-radius: 7px;")
        self.lamp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lamp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lamp.setObjectName("lamp")
        self.frame_motor = QtWidgets.QFrame(asideCardInspect)
        self.frame_motor.setGeometry(QtCore.QRect(20, 370, 111, 71))
        self.frame_motor.setStyleSheet("#frame_motor{\n"
"    background-color:white;\n"
"    border: 1px solid #808080;\n"
"    border-radius: 8px;\n"
"}")
        self.frame_motor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_motor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_motor.setObjectName("frame_motor")
        self.label_22 = QtWidgets.QLabel(self.frame_motor)
        self.label_22.setGeometry(QtCore.QRect(48, 16, 47, 13))
        self.label_22.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_motor)
        self.pushButton_3.setGeometry(QtCore.QRect(6, 6, 32, 32))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: #ebebeb;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("AppDesign\\../icons/gear-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.frame_motor)
        self.label_11.setGeometry(QtCore.QRect(32, 44, 47, 13))
        self.label_11.setObjectName("label_11")
        self.frame_imu = QtWidgets.QFrame(asideCardInspect)
        self.frame_imu.setGeometry(QtCore.QRect(160, 260, 151, 241))
        self.frame_imu.setStyleSheet("#frame_imu{\n"
"    background-color:white;\n"
"    border: 1px solid #808080;\n"
"    border-radius: 8px;\n"
"}")
        self.frame_imu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imu.setObjectName("frame_imu")
        self.label_12 = QtWidgets.QLabel(self.frame_imu)
        self.label_12.setGeometry(QtCore.QRect(43, 16, 47, 13))
        self.label_12.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_imu)
        self.pushButton_4.setGeometry(QtCore.QRect(6, 6, 32, 32))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: #ebebeb;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(self.frame_imu)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_imu)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_imu)
        self.label_15.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.label_15.setObjectName("label_15")
        self.line = QtWidgets.QFrame(self.frame_imu)
        self.line.setGeometry(QtCore.QRect(20, 50, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_16 = QtWidgets.QLabel(self.frame_imu)
        self.label_16.setGeometry(QtCore.QRect(108, 30, 31, 16))
        self.label_16.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_imu)
        self.label_17.setGeometry(QtCore.QRect(110, 100, 31, 16))
        self.label_17.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.line_2 = QtWidgets.QFrame(self.frame_imu)
        self.line_2.setGeometry(QtCore.QRect(20, 120, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_18 = QtWidgets.QLabel(self.frame_imu)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_imu)
        self.label_19.setGeometry(QtCore.QRect(10, 150, 47, 13))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_imu)
        self.label_20.setGeometry(QtCore.QRect(70, 130, 47, 13))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_imu)
        self.label_21.setGeometry(QtCore.QRect(100, 170, 41, 20))
        self.label_21.setStyleSheet("QLabel{\n"
"    color: #808080;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.line_3 = QtWidgets.QFrame(self.frame_imu)
        self.line_3.setGeometry(QtCore.QRect(20, 190, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_23 = QtWidgets.QLabel(self.frame_imu)
        self.label_23.setGeometry(QtCore.QRect(10, 200, 47, 13))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_imu)
        self.label_24.setGeometry(QtCore.QRect(70, 200, 47, 13))
        self.label_24.setObjectName("label_24")
        self.pbCloseInspect = QtWidgets.QPushButton(asideCardInspect)
        self.pbCloseInspect.setGeometry(QtCore.QRect(280, 10, 32, 32))
        self.pbCloseInspect.setStyleSheet("QPushButton{\n"
"    background-color: #ebebeb;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"}")
        self.pbCloseInspect.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("AppDesign\\../icons/xmark-solid-full_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCloseInspect.setIcon(icon3)
        self.pbCloseInspect.setObjectName("pbCloseInspect")
        self.image_container = QtWidgets.QLabel(asideCardInspect)
        self.image_container.setGeometry(QtCore.QRect(26, 72, 281, 161))
        self.image_container.setStyleSheet("#image_container{\n"
"    border-radius: 12px;\n"
"}")
        self.image_container.setText("")
        self.image_container.setPixmap(QtGui.QPixmap("AppDesign\\../images/AGV.webp"))
        self.image_container.setScaledContents(True)
        self.image_container.setObjectName("image_container")

        self.retranslateUi(asideCardInspect)
        QtCore.QMetaObject.connectSlotsByName(asideCardInspect)

    def retranslateUi(self, asideCardInspect):
        _translate = QtCore.QCoreApplication.translate
        asideCardInspect.setWindowTitle(_translate("asideCardInspect", "Form"))
        self.label_3.setText(_translate("asideCardInspect", "Ultrasonic"))
        self.label_4.setText(_translate("asideCardInspect", "L : 123"))
        self.label_5.setText(_translate("asideCardInspect", "M : 123"))
        self.label_6.setText(_translate("asideCardInspect", "R : 123"))
        self.label.setText(_translate("asideCardInspect", "ROBOT-123"))
        self.label_2.setText(_translate("asideCardInspect", "Online"))
        self.label_22.setText(_translate("asideCardInspect", "Motor"))
        self.label_11.setText(_translate("asideCardInspect", "123 Rpm"))
        self.label_12.setText(_translate("asideCardInspect", "IMU"))
        self.label_13.setText(_translate("asideCardInspect", "Ax : 123"))
        self.label_14.setText(_translate("asideCardInspect", "Ax : 123"))
        self.label_15.setText(_translate("asideCardInspect", "Ay: 123"))
        self.label_16.setText(_translate("asideCardInspect", "Accel"))
        self.label_17.setText(_translate("asideCardInspect", "Gyro"))
        self.label_18.setText(_translate("asideCardInspect", "Ax : 123"))
        self.label_19.setText(_translate("asideCardInspect", "Ax : 123"))
        self.label_20.setText(_translate("asideCardInspect", "Ay: 123"))
        self.label_21.setText(_translate("asideCardInspect", "Derived"))
        self.label_23.setText(_translate("asideCardInspect", "Ax : 123"))
        self.label_24.setText(_translate("asideCardInspect", "Ay: 123"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    asideCardInspect = QtWidgets.QWidget()
    ui = Ui_asideCardInspect()
    ui.setupUi(asideCardInspect)
    asideCardInspect.show()
    sys.exit(app.exec_())
