# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlClientPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientAccessPup(object):
    def setupUi(self, ClientAccessPup):
        ClientAccessPup.setObjectName("ClientAccessPup")
        ClientAccessPup.resize(323, 242)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/remote-control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientAccessPup.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(ClientAccessPup)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.devid = QtWidgets.QLineEdit(ClientAccessPup)
        self.devid.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.devid.setObjectName("devid")
        self.button_takeover = QtWidgets.QPushButton(ClientAccessPup)
        self.button_takeover.setGeometry(QtCore.QRect(10, 62, 75, 51))
        self.button_takeover.setObjectName("button_takeover")
        self.button_up = QtWidgets.QPushButton(ClientAccessPup)
        self.button_up.setGeometry(QtCore.QRect(120, 102, 75, 41))
        self.button_up.setObjectName("button_up")
        self.button_down = QtWidgets.QPushButton(ClientAccessPup)
        self.button_down.setGeometry(QtCore.QRect(120, 170, 75, 41))
        self.button_down.setObjectName("button_down")
        self.button_left = QtWidgets.QPushButton(ClientAccessPup)
        self.button_left.setGeometry(QtCore.QRect(20, 140, 75, 41))
        self.button_left.setObjectName("button_left")
        self.button_right = QtWidgets.QPushButton(ClientAccessPup)
        self.button_right.setGeometry(QtCore.QRect(220, 140, 75, 41))
        self.button_right.setObjectName("button_right")
        self.lamp = QtWidgets.QFrame(ClientAccessPup)
        self.lamp.setGeometry(QtCore.QRect(130, 30, 20, 20))
        self.lamp.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;")
        self.lamp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lamp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lamp.setObjectName("lamp")

        self.retranslateUi(ClientAccessPup)
        QtCore.QMetaObject.connectSlotsByName(ClientAccessPup)

    def retranslateUi(self, ClientAccessPup):
        _translate = QtCore.QCoreApplication.translate
        ClientAccessPup.setWindowTitle(_translate("ClientAccessPup", "Access"))
        self.label.setText(_translate("ClientAccessPup", "DevId"))
        self.button_takeover.setText(_translate("ClientAccessPup", "Take Over"))
        self.button_up.setText(_translate("ClientAccessPup", "Up"))
        self.button_down.setText(_translate("ClientAccessPup", "Down"))
        self.button_left.setText(_translate("ClientAccessPup", "Left"))
        self.button_right.setText(_translate("ClientAccessPup", "Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientAccessPup = QtWidgets.QWidget()
    ui = Ui_ClientAccessPup()
    ui.setupUi(ClientAccessPup)
    ClientAccessPup.show()
    sys.exit(app.exec_())
