# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createClientPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateClientPup(object):
    def setupUi(self, CreateClientPup):
        CreateClientPup.setObjectName("CreateClientPup")
        CreateClientPup.resize(273, 261)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/pencil-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateClientPup.setWindowIcon(icon)
        self.Button_Create = QtWidgets.QPushButton(CreateClientPup)
        self.Button_Create.setGeometry(QtCore.QRect(50, 170, 75, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Create.setIcon(icon1)
        self.Button_Create.setObjectName("Button_Create")
        self.Button_Cancel = QtWidgets.QPushButton(CreateClientPup)
        self.Button_Cancel.setGeometry(QtCore.QRect(150, 170, 75, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Cancel.setIcon(icon2)
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.Input_DeviceId = QtWidgets.QLineEdit(CreateClientPup)
        self.Input_DeviceId.setGeometry(QtCore.QRect(80, 80, 113, 20))
        self.Input_DeviceId.setMaxLength(5)
        self.Input_DeviceId.setObjectName("Input_DeviceId")
        self.lineEdit_2 = QtWidgets.QLineEdit(CreateClientPup)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 130, 113, 20))
        self.lineEdit_2.setMaxLength(20)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Input_Signature = QtWidgets.QLabel(CreateClientPup)
        self.Input_Signature.setGeometry(QtCore.QRect(80, 60, 47, 13))
        self.Input_Signature.setObjectName("Input_Signature")
        self.label_2 = QtWidgets.QLabel(CreateClientPup)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CreateClientPup)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(CreateClientPup)
        QtCore.QMetaObject.connectSlotsByName(CreateClientPup)

    def retranslateUi(self, CreateClientPup):
        _translate = QtCore.QCoreApplication.translate
        CreateClientPup.setWindowTitle(_translate("CreateClientPup", "Register Client"))
        self.Button_Create.setText(_translate("CreateClientPup", "Create"))
        self.Button_Cancel.setText(_translate("CreateClientPup", "Cancel"))
        self.Input_Signature.setText(_translate("CreateClientPup", "Device Id"))
        self.label_2.setText(_translate("CreateClientPup", "Device Signature"))
        self.label_3.setText(_translate("CreateClientPup", "Create New Client"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateClientPup = QtWidgets.QWidget()
    ui = Ui_CreateClientPup()
    ui.setupUi(CreateClientPup)
    CreateClientPup.show()
    sys.exit(app.exec_())
