# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteClientPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteClientPup(object):
    def setupUi(self, DeleteClientPup):
        DeleteClientPup.setObjectName("DeleteClientPup")
        DeleteClientPup.resize(254, 166)
        self.Input_Id = QtWidgets.QLineEdit(DeleteClientPup)
        self.Input_Id.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.Input_Id.setObjectName("Input_Id")
        self.Input_Signature_2 = QtWidgets.QLabel(DeleteClientPup)
        self.Input_Signature_2.setGeometry(QtCore.QRect(70, 30, 47, 13))
        self.Input_Signature_2.setObjectName("Input_Signature_2")
        self.Button_Delete = QtWidgets.QPushButton(DeleteClientPup)
        self.Button_Delete.setGeometry(QtCore.QRect(40, 100, 75, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Delete.setIcon(icon)
        self.Button_Delete.setObjectName("Button_Delete")
        self.Button_Cancel = QtWidgets.QPushButton(DeleteClientPup)
        self.Button_Cancel.setGeometry(QtCore.QRect(140, 100, 75, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Cancel.setIcon(icon1)
        self.Button_Cancel.setObjectName("Button_Cancel")

        self.retranslateUi(DeleteClientPup)
        QtCore.QMetaObject.connectSlotsByName(DeleteClientPup)

    def retranslateUi(self, DeleteClientPup):
        _translate = QtCore.QCoreApplication.translate
        DeleteClientPup.setWindowTitle(_translate("DeleteClientPup", "Form"))
        self.Input_Signature_2.setText(_translate("DeleteClientPup", "Device Id"))
        self.Button_Delete.setText(_translate("DeleteClientPup", "Delete"))
        self.Button_Cancel.setText(_translate("DeleteClientPup", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteClientPup = QtWidgets.QWidget()
    ui = Ui_DeleteClientPup()
    ui.setupUi(DeleteClientPup)
    DeleteClientPup.show()
    sys.exit(app.exec_())
