# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NodeTable = QtWidgets.QTableWidget(self.centralwidget)
        self.NodeTable.setGeometry(QtCore.QRect(40, 460, 521, 192))
        self.NodeTable.setObjectName("NodeTable")
        self.NodeTable.setColumnCount(0)
        self.NodeTable.setRowCount(0)
        self.NodeTable.horizontalHeader().setCascadingSectionResizes(True)
        self.NodeTable.horizontalHeader().setMinimumSectionSize(42)
        self.NodeTable.horizontalHeader().setStretchLastSection(True)
        self.NodeTable.verticalHeader().setVisible(False)
        self.NodeTable.verticalHeader().setHighlightSections(False)
        self.SwarmView = QtWidgets.QGraphicsView(self.centralwidget)
        self.SwarmView.setGeometry(QtCore.QRect(40, 20, 521, 371))
        self.SwarmView.setObjectName("SwarmView")
        self.AddNodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddNodeButton.setGeometry(QtCore.QRect(500, 410, 61, 31))
        self.AddNodeButton.setObjectName("AddNodeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddNodeButton.setText(_translate("MainWindow", "Add Slave"))
