# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/mainScreen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 1042)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 61, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/bars-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(69, 9, 211, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vLayout_aside = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vLayout_aside.setContentsMargins(0, 0, 0, 0)
        self.vLayout_aside.setObjectName("vLayout_aside")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
