# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 800)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NodeTable = QtWidgets.QTableWidget(self.centralwidget)
        self.NodeTable.setGeometry(QtCore.QRect(10, 510, 531, 241))
        self.NodeTable.setObjectName("NodeTable")
        self.NodeTable.setColumnCount(0)
        self.NodeTable.setRowCount(0)
        self.NodeTable.horizontalHeader().setCascadingSectionResizes(True)
        self.NodeTable.horizontalHeader().setMinimumSectionSize(42)
        self.NodeTable.horizontalHeader().setStretchLastSection(True)
        self.NodeTable.verticalHeader().setVisible(False)
        self.NodeTable.verticalHeader().setHighlightSections(False)
        self.AddNodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddNodeButton.setGeometry(QtCore.QRect(460, 470, 81, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/plus-solid-full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddNodeButton.setIcon(icon)
        self.AddNodeButton.setObjectName("AddNodeButton")
        self.AccessButton = QtWidgets.QPushButton(self.centralwidget)
        self.AccessButton.setGeometry(QtCore.QRect(160, 470, 75, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/remote-control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccessButton.setIcon(icon1)
        self.AccessButton.setObjectName("AccessButton")
        self.DelNodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.DelNodeButton.setGeometry(QtCore.QRect(364, 470, 81, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("AppDesign\\../icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DelNodeButton.setIcon(icon2)
        self.DelNodeButton.setIconSize(QtCore.QSize(12, 12))
        self.DelNodeButton.setObjectName("DelNodeButton")
        self.InspectButton = QtWidgets.QPushButton(self.centralwidget)
        self.InspectButton.setGeometry(QtCore.QRect(250, 470, 101, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("AppDesign\\../icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InspectButton.setIcon(icon3)
        self.InspectButton.setObjectName("InspectButton")
        self.TerminalDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.TerminalDisplay.setEnabled(True)
        self.TerminalDisplay.setGeometry(QtCore.QRect(10, 10, 531, 231))
        self.TerminalDisplay.setObjectName("TerminalDisplay")
        self.SwarmWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.SwarmWidget.setGeometry(QtCore.QRect(549, 9, 841, 741))
        self.SwarmWidget.setObjectName("SwarmWidget")
        self.programLoad = QtWidgets.QPushButton(self.centralwidget)
        self.programLoad.setGeometry(QtCore.QRect(460, 432, 81, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("AppDesign\\../icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.programLoad.setIcon(icon4)
        self.programLoad.setObjectName("programLoad")
        self.programExec = QtWidgets.QPushButton(self.centralwidget)
        self.programExec.setGeometry(QtCore.QRect(364, 432, 81, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("AppDesign\\../icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.programExec.setIcon(icon5)
        self.programExec.setObjectName("programExec")
        self.fileNameLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameLabel.setGeometry(QtCore.QRect(10, 432, 341, 31))
        self.fileNameLabel.setReadOnly(True)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.defineMapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.defineMapBtn.setGeometry(QtCore.QRect(54, 470, 91, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("AppDesign\\../icons/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defineMapBtn.setIcon(icon6)
        self.defineMapBtn.setObjectName("defineMapBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NodeTable.setSortingEnabled(False)
        self.AddNodeButton.setText(_translate("MainWindow", "Add Slave"))
        self.AccessButton.setText(_translate("MainWindow", "Access"))
        self.DelNodeButton.setText(_translate("MainWindow", "Del Slave"))
        self.InspectButton.setText(_translate("MainWindow", "Inspect Slave"))
        self.programLoad.setText(_translate("MainWindow", "Load"))
        self.programExec.setText(_translate("MainWindow", "Exec"))
        self.defineMapBtn.setText(_translate("MainWindow", "Define Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
