# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualControlDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManControl(object):
    def setupUi(self, ManControl):
        ManControl.setObjectName("ManControl")
        ManControl.resize(400, 300)
        ManControl.setMaximumSize(QtCore.QSize(400, 300))
        self.buttonBox = QtWidgets.QDialogButtonBox(ManControl)
        self.buttonBox.setGeometry(QtCore.QRect(30, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(ManControl)
        self.pushButton.setGeometry(QtCore.QRect(160, 52, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ManControl)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 170, 75, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(ManControl)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 110, 75, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(ManControl)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 110, 75, 41))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(ManControl)
        self.buttonBox.accepted.connect(ManControl.accept) # type: ignore
        self.buttonBox.rejected.connect(ManControl.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ManControl)

    def retranslateUi(self, ManControl):
        _translate = QtCore.QCoreApplication.translate
        ManControl.setWindowTitle(_translate("ManControl", "Dialog"))
        self.pushButton.setText(_translate("ManControl", "Forward"))
        self.pushButton_2.setText(_translate("ManControl", "Backward"))
        self.pushButton_3.setText(_translate("ManControl", "Right"))
        self.pushButton_4.setText(_translate("ManControl", "Left"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManControl = QtWidgets.QDialog()
    ui = Ui_ManControl()
    ui.setupUi(ManControl)
    ManControl.show()
    sys.exit(app.exec_())
