# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/mapGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapGenerator(object):
    def setupUi(self, MapGenerator):
        MapGenerator.setObjectName("MapGenerator")
        MapGenerator.resize(561, 456)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MapGenerator.setWindowIcon(icon)
        self.drawBtn = QtWidgets.QPushButton(MapGenerator)
        self.drawBtn.setGeometry(QtCore.QRect(454, 10, 81, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/marker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drawBtn.setIcon(icon1)
        self.drawBtn.setObjectName("drawBtn")
        self.EraseBtn = QtWidgets.QPushButton(MapGenerator)
        self.EraseBtn.setGeometry(QtCore.QRect(454, 90, 81, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("AppDesign\\../icons/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EraseBtn.setIcon(icon2)
        self.EraseBtn.setObjectName("EraseBtn")
        self.ClearBtn = QtWidgets.QPushButton(MapGenerator)
        self.ClearBtn.setGeometry(QtCore.QRect(454, 130, 81, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("AppDesign\\../icons/broom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearBtn.setIcon(icon3)
        self.ClearBtn.setObjectName("ClearBtn")
        self.saveBtn = QtWidgets.QPushButton(MapGenerator)
        self.saveBtn.setGeometry(QtCore.QRect(454, 362, 81, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("AppDesign\\../icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon4)
        self.saveBtn.setObjectName("saveBtn")
        self.cancelBtn = QtWidgets.QPushButton(MapGenerator)
        self.cancelBtn.setGeometry(QtCore.QRect(454, 400, 81, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("AppDesign\\../icons/cross-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBtn.setIcon(icon5)
        self.cancelBtn.setObjectName("cancelBtn")
        self.drawArea = QtWidgets.QWidget(MapGenerator)
        self.drawArea.setGeometry(QtCore.QRect(9, 9, 420, 420))
        self.drawArea.setObjectName("drawArea")
        self.addLandmarkBtn = QtWidgets.QPushButton(MapGenerator)
        self.addLandmarkBtn.setGeometry(QtCore.QRect(454, 50, 81, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("AppDesign\\../icons/destination.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addLandmarkBtn.setIcon(icon6)
        self.addLandmarkBtn.setObjectName("addLandmarkBtn")
        self.OptionBtn = QtWidgets.QPushButton(MapGenerator)
        self.OptionBtn.setGeometry(QtCore.QRect(454, 170, 81, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("AppDesign\\../icons/cogwheel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OptionBtn.setIcon(icon7)
        self.OptionBtn.setObjectName("OptionBtn")

        self.retranslateUi(MapGenerator)
        QtCore.QMetaObject.connectSlotsByName(MapGenerator)

    def retranslateUi(self, MapGenerator):
        _translate = QtCore.QCoreApplication.translate
        MapGenerator.setWindowTitle(_translate("MapGenerator", "Map Maker"))
        self.drawBtn.setText(_translate("MapGenerator", "Draw"))
        self.EraseBtn.setText(_translate("MapGenerator", "Erase"))
        self.ClearBtn.setText(_translate("MapGenerator", "Erase All"))
        self.saveBtn.setText(_translate("MapGenerator", "Save"))
        self.cancelBtn.setText(_translate("MapGenerator", "Cancel"))
        self.addLandmarkBtn.setText(_translate("MapGenerator", "Landmark"))
        self.OptionBtn.setText(_translate("MapGenerator", "Option"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MapGenerator = QtWidgets.QWidget()
    ui = Ui_MapGenerator()
    ui.setupUi(MapGenerator)
    MapGenerator.show()
    sys.exit(app.exec_())
