# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDesign/mapGeneratorOption.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapGeneratorOption(object):
    def setupUi(self, MapGeneratorOption):
        MapGeneratorOption.setObjectName("MapGeneratorOption")
        MapGeneratorOption.resize(245, 281)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppDesign\\../icons/cogwheel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MapGeneratorOption.setWindowIcon(icon)
        self.unit_ComboBox = QtWidgets.QComboBox(MapGeneratorOption)
        self.unit_ComboBox.setGeometry(QtCore.QRect(10, 40, 81, 22))
        self.unit_ComboBox.setObjectName("unit_ComboBox")
        self.unit_ComboBox.addItem("")
        self.unit_ComboBox.addItem("")
        self.label = QtWidgets.QLabel(MapGeneratorOption)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.mapWidth_Input = QtWidgets.QSpinBox(MapGeneratorOption)
        self.mapWidth_Input.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.mapWidth_Input.setMinimum(1)
        self.mapWidth_Input.setMaximum(999999)
        self.mapWidth_Input.setObjectName("mapWidth_Input")
        self.mapHeight_Input = QtWidgets.QSpinBox(MapGeneratorOption)
        self.mapHeight_Input.setGeometry(QtCore.QRect(130, 90, 81, 22))
        self.mapHeight_Input.setMinimum(1)
        self.mapHeight_Input.setMaximum(999999)
        self.mapHeight_Input.setObjectName("mapHeight_Input")
        self.label_4 = QtWidgets.QLabel(MapGeneratorOption)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(MapGeneratorOption)
        self.label_5.setGeometry(QtCore.QRect(130, 70, 61, 16))
        self.label_5.setObjectName("label_5")
        self.cellSpace_Input = QtWidgets.QSpinBox(MapGeneratorOption)
        self.cellSpace_Input.setGeometry(QtCore.QRect(10, 140, 81, 22))
        self.cellSpace_Input.setMinimum(1)
        self.cellSpace_Input.setMaximum(999999)
        self.cellSpace_Input.setObjectName("cellSpace_Input")
        self.label_6 = QtWidgets.QLabel(MapGeneratorOption)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_6.setObjectName("label_6")
        self.unit_label_1 = QtWidgets.QLabel(MapGeneratorOption)
        self.unit_label_1.setGeometry(QtCore.QRect(100, 92, 21, 16))
        self.unit_label_1.setObjectName("unit_label_1")
        self.unit_label_2 = QtWidgets.QLabel(MapGeneratorOption)
        self.unit_label_2.setGeometry(QtCore.QRect(220, 92, 21, 16))
        self.unit_label_2.setObjectName("unit_label_2")
        self.unit_label_3 = QtWidgets.QLabel(MapGeneratorOption)
        self.unit_label_3.setGeometry(QtCore.QRect(100, 142, 21, 16))
        self.unit_label_3.setObjectName("unit_label_3")
        self.applyBtn = QtWidgets.QPushButton(MapGeneratorOption)
        self.applyBtn.setGeometry(QtCore.QRect(10, 180, 81, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("AppDesign\\../icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyBtn.setIcon(icon1)
        self.applyBtn.setObjectName("applyBtn")
        self.cancelBtn = QtWidgets.QPushButton(MapGeneratorOption)
        self.cancelBtn.setGeometry(QtCore.QRect(10, 220, 81, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("AppDesign\\../icons/cross-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBtn.setIcon(icon2)
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(MapGeneratorOption)
        QtCore.QMetaObject.connectSlotsByName(MapGeneratorOption)

    def retranslateUi(self, MapGeneratorOption):
        _translate = QtCore.QCoreApplication.translate
        MapGeneratorOption.setWindowTitle(_translate("MapGeneratorOption", "Option"))
        self.unit_ComboBox.setItemText(0, _translate("MapGeneratorOption", "Meter"))
        self.unit_ComboBox.setItemText(1, _translate("MapGeneratorOption", "Centimeter"))
        self.label.setText(_translate("MapGeneratorOption", "Map unit"))
        self.label_4.setText(_translate("MapGeneratorOption", "Map Width"))
        self.label_5.setText(_translate("MapGeneratorOption", "Map_Height"))
        self.label_6.setText(_translate("MapGeneratorOption", "Cell Spacing"))
        self.unit_label_1.setText(_translate("MapGeneratorOption", "Cm"))
        self.unit_label_2.setText(_translate("MapGeneratorOption", "Cm"))
        self.unit_label_3.setText(_translate("MapGeneratorOption", "Cm"))
        self.applyBtn.setText(_translate("MapGeneratorOption", "Apply"))
        self.cancelBtn.setText(_translate("MapGeneratorOption", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MapGeneratorOption = QtWidgets.QWidget()
    ui = Ui_MapGeneratorOption()
    ui.setupUi(MapGeneratorOption)
    MapGeneratorOption.show()
    sys.exit(app.exec_())
