# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotNodeFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RobotNode(object):
    def setupUi(self, RobotNode):
        RobotNode.setObjectName("RobotNode")
        RobotNode.resize(200, 200)
        RobotNode.setMinimumSize(QtCore.QSize(200, 200))
        RobotNode.setAutoFillBackground(False)
        RobotNode.setFrameShape(QtWidgets.QFrame.Box)
        RobotNode.setLineWidth(1)
        self.label_2 = QtWidgets.QLabel(RobotNode)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RobotNode)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(RobotNode)
        self.label_5.setGeometry(QtCore.QRect(60, 60, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(RobotNode)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(RobotNode)
        self.label_4.setGeometry(QtCore.QRect(90, 40, 31, 16))
        self.label_4.setObjectName("label_4")
        self.ShowJson = QtWidgets.QPushButton(RobotNode)
        self.ShowJson.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.ShowJson.setObjectName("ShowJson")
        self.ControlMode = QtWidgets.QPushButton(RobotNode)
        self.ControlMode.setGeometry(QtCore.QRect(90, 170, 75, 23))
        self.ControlMode.setObjectName("ControlMode")

        self.retranslateUi(RobotNode)
        QtCore.QMetaObject.connectSlotsByName(RobotNode)

    def retranslateUi(self, RobotNode):
        _translate = QtCore.QCoreApplication.translate
        RobotNode.setWindowTitle(_translate("RobotNode", "Frame"))
        self.label_2.setText(_translate("RobotNode", "Control Mode :"))
        self.label_3.setText(_translate("RobotNode", "Status :"))
        self.label_5.setText(_translate("RobotNode", "None"))
        self.label.setText(_translate("RobotNode", "001"))
        self.label_4.setText(_translate("RobotNode", "None"))
        self.ShowJson.setText(_translate("RobotNode", "Show Raw"))
        self.ControlMode.setText(_translate("RobotNode", "Control Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RobotNode = QtWidgets.QFrame()
    ui = Ui_RobotNode()
    ui.setupUi(RobotNode)
    RobotNode.show()
    sys.exit(app.exec_())
